
camelCase: true
customImports: {}
dateParser: timestamp
defaultSchemas: [] # ["public"] for PostgreSQL.
dialect: sqlite
domains: true
envFile: .env
excludePattern: null
includePattern: null
logLevel: "warn"
numericParser: "string"
outFile: "./node_modules/kysely-codegen/dist/db.d.ts"
overrides: {}
partitions: false
print: false
runtimeEnums: false
singularize: false
typeMapping: {}
TypeOnlyImports: true
url: "env(DATABASE_URL)"
verify: false